version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urbanmedic

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./app:/code
    ports:
      - '8080:8080'
    depends_on:
      - db
